In [1]:
# Q1) Create three lists of principle amount, rate of interest and time duration of 1000 farmers. 
#Compute Simple Interest of 1000 farmers and put it in a List
p=[100,200,300]
t=[2,4,6]
r=[5,10,15]
si_list=[]

for i in range(3):
    si_list.append(p[i]*t[i]*r[i]/100)
si_list    

[10.0, 80.0, 270.0]

In [29]:
# Q2) Create three nd arrays of principle amount, rate of interest and time duration of 1000 farmers
# Compute corresponding Simple Interest of 1000 farmers in and array.
import numpy as np
p=np.random.randint(500,2000,size=1000)
t=np.random.randint(0.2,2,size=1000)
r=np.random.randint(1,6,size=1000)
si=(p*r*t/100)
si[:1000]    

array([44.4 , 16.75, 12.38, 39.24,  0.  , 58.85,  0.  , 28.14, 35.  ,
       49.28, 13.94,  0.  ,  0.  , 35.4 , 56.91,  0.  , 11.17, 21.36,
       15.56,  0.  ,  0.  , 23.18, 15.  , 10.91, 55.53,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  , 56.1 , 20.48, 54.8 ,  0.  ,  0.  ,  0.  ,
        0.  , 48.66,  0.  ,  0.  ,  0.  ,  0.  , 15.81, 51.35, 28.29,
       68.15, 60.76,  0.  ,  0.  ,  0.  , 35.8 , 16.68, 12.11,  0.  ,
       32.68, 26.4 ,  0.  ,  0.  , 48.84,  0.  ,  0.  , 41.88, 13.32,
        0.  ,  0.  ,  0.  , 41.48, 44.36,  0.  ,  0.  , 48.68,  0.  ,
       22.83, 12.98, 49.11,  0.  ,  0.  ,  0.  ,  0.  , 27.02,  0.  ,
        0.  ,  0.  , 48.24, 42.7 ,  0.  ,  0.  ,  0.  ,  0.  , 62.55,
       47.31, 45.81, 33.84, 19.14, 12.79, 18.08, 28.23,  0.  , 18.58,
       32.32,  9.48, 41.37, 28.89,  0.  ,  0.  , 51.7 , 17.14, 59.94,
       19.46, 84.75,  0.  , 69.92, 37.3 ,  0.  , 34.45,  0.  ,  0.  ,
        0.  , 51.2 ,  0.  ,  0.  , 39.45, 16.34,  0.  , 46.5 , 55.96,
        0.  , 58.76,

In [53]:
# Q3) Create a ndarray ‘a’ from [1,2,3,4,5] and identify a[1],a[2:5], update a[1] to 99 and a[2] to ‘abc’.
import numpy as np
a=np.array([1,2,3,4,5])
print(a[1])
print(a[2:5])
a[1]=99
print('updated array:',a)
a[2]='abc'
a

2
[3 4 5]
updated array: [ 1 99  3  4  5]


ValueError: invalid literal for int() with base 10: 'abc'

In [56]:
# Q4) Use test=[[1,2,3], [4,5,6], [7,8,9]] to create multi nd array ‘data’ and check its shape.
import pandas as pd
test=[[1,2,3], [4,5,6], [7,8,9]]
data=np.array(test)
print(data.shape)

(3, 3)


In [62]:
# Q5) Create data=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) using ‘arrange’ function and create array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]) 
import pandas as pd
data=np.arange(start=0,stop=10,step=1)
print('data:',data)
test=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
print('test',test)


data: [0 1 2 3 4 5 6 7 8 9]
test [[0 1 2 3 4]
 [5 6 7 8 9]]


In [74]:
#Q6) Create array([1, 2, 3, 3, 2, 1, 1, 2, 3]) from [1,2,3] and [3,2,1] 
import numpy as np
a=np.array([1,2,3])
b=np.array([3,2,1])
c=np.concatenate((a,b,a))
c

array([1, 2, 3, 3, 2, 1, 1, 2, 3])

In [84]:
#Q7) Create array([[1, 2, 3], [5, 6, 7],[1, 2, 3], [5, 6, 7]]) from [ [1,2,3],[5,6,7]] 
import numpy as np
a=np.array([[1,2,3],[5,6,7]])
c=np.vstack((a,a))
c

array([[1, 2, 3],
       [5, 6, 7],
       [1, 2, 3],
       [5, 6, 7]])

In [87]:
#Q8) Create array([[ 4, 44, 444], [ 1, 2, 3], [ 5, 6, 7]]) from [4,44,444] and [ [1,2,3],[5,6,7]]
import numpy as np
a=np.array([4,44,444])
b=np.array([[1,2,3],[5,6,7]])
c=np.vstack((a,b))
c

array([[  4,  44, 444],
       [  1,   2,   3],
       [  5,   6,   7]])

In [91]:
#Q9) From [1,2,77,4,5,9,6,7,7,9] create array([ 1, 2, 77]), array([4, 5]), array([9, 6, 7]) and array([7, 9])

import numpy as np
a=np.array([1,2,77,4,5,9,6,7,7,9])
newarray=np.array_split(a,[3,5,8])
newarray

[array([ 1,  2, 77]), array([4, 5]), array([9, 6, 7]), array([7, 9])]

In [93]:
#Q10) If data= array([[1, 2, 3], [4, 5, 6]]), find data+data and data*data 
import numpy as np
data=np.array([[1, 2, 3], [4, 5, 6]])
a=data+data
print(a)
b=data*data
print(b)


[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]


In [94]:
#Q11) If data= array([[1, 2, 3], [4, 5, 6]]) and data_1= array([[10,20], [30,40]]), find data*data_1 and data_1*data
import numpy as np
data=np.array([[1, 2, 3], [4, 5, 6]])
data_1=np.array([[10,20], [30,40]])
print(data*data_1)
print(data_1+data)


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [96]:
#Q12) Get array ([[14, 32], [32, 77]]) from data= array([[1, 2, 3], [4, 5, 6]])
import numpy as np
data=np.array([[1, 2, 3], [4, 5, 6]])
result=np.dot(data,data.T)
print(result)


[[14 32]
 [32 77]]


In [97]:
#Q13) Get array([[9, 0], [4, 0]]) from [[9,3],[4,5]] and [[1,0],[1,0]]

import numpy as np
data=np.array([[9, 3], [4, 5]])
data1=np.array([[1,0],[1,0]])
result=data*data1
result

array([[9, 0],
       [4, 0]])

In [ ]:
#Q14) Create array([1, 2, 3, 4, 5]) and get sum of all elements of nd array and product
